### ISSUE TITLE
Run on Ubuntu: "404 page not found"

### ISSUE THREAD

**Issue by EnziinSystem** [Qolzam/telar-cli#2] opened 2020-06-14 04:30 UTC
* Ubuntu 20.04
* Download telar-cli and run
`./telar-cli`
Result: open http://localhost:8000/
`404 page not found`

**Comment by Qolzam** [comment] 2020-06-15 13:07
Thank you @EnziinSystem for feedback 👍 . I understand the issue and I will try to fix it as soon as possible.

**Comment by EnziinSystem** [comment] 2020-06-15 13:21
@Qolzam Thank you!

**Comment by Qolzam** [comment] 2020-06-16 08:51
@EnziinSystem , I built another CLI file for Linux, please try to [download](https://github.com/Qolzam/telar-cli/releases/download/v0.1.0/telar) new binary update and let me know if any issue.
Thank you again!

**Comment by EnziinSystem** [comment] 2020-06-16 10:10
It's still 404 at http://localhost:8000
:+1:

**Comment by EnziinSystem** [comment] 2020-06-27 06:43
@Qolzam Hello, the Telar Social project still in progress development, isn't it?
Thanks!

**Comment by Qolzam** [comment] 2020-06-27 13:13
Hi @EnziinSystem, sorry for late reply I could not reproduce on two different PC. But as I had this issue at first on Ubuntu I need check deeply to reproduce and understand the cause of your issue. As soon as I make a time I will investigate more. 
By the way can I have some details about your ubuntu like version?
Also can you try to build this app on your system to check the behaviour?

Thank you :)

**Comment by EnziinSystem** [comment] 2020-06-27 13:35
Hello, my environment:
```
kevin@enziin:~$ uname -a
Linux enziin 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I will try to build this app on Ubuntu.
Otherwise, I want to question the future of Telar Social, will you still develop it?
Thanks.

**Comment by Qolzam** [comment] 2020-06-27 14:19
Thank you @EnziinSystem for the information. Can I have output of `lsb_release -a` command too?

> Otherwise, I want to question the future of Telar Social, will you still develop it?

Yes, I am developing and as you know this is an open-source free project .The development but is slow as I am busy with other business projects ;)
Anyway I appreciate any contribution 👍

**Comment by EnziinSystem** [comment] 2020-06-27 14:29
Yes,
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
For Telar Social, please spent time complete developer documents.
Thanks.

**Comment by Qolzam** [comment] 2020-07-04 07:24
Dear @EnziinSystem, please try new fix update. Let me know if any issue.

Thank you 🙂

**Comment by EnziinSystem** [comment] 2020-07-04 13:25
Can you rebuild and release new version tag?
Thanks in advance.

**Comment by Qolzam** [comment] 2020-07-04 14:08
Dear @EnziinSystem, you can use [V0.1.1](https://github.com/Qolzam/telar-cli/releases/tag/v0.1.1). 💪

**Comment by EnziinSystem** [comment] 2020-07-06 09:49
It's worked, excellent!
Please complete document development for the social projects, I can become a contributor.
Thanks.

**Comment by Qolzam** [comment] 2020-07-06 10:13
@EnziinSystem happy to hear it works for you :) 

About the document as the time is narrow, could you please help me with [a feedback](https://github.com/Qolzam/feedback/issues/4)? It can help you to get what you need faster and help me to understand developers need well. Any contribution is very welcome 🙂

I am going to close this issue as your approvement. Please feel free to reopen if you face with this issue again.

Thank you!

**Closed by Qolzam** 2020-07-06 10:13 UTC
Labels: bug
